// Generated by gencpp from file path_planning/PathParam.msg
// DO NOT EDIT!


#ifndef PATH_PLANNING_MESSAGE_PATHPARAM_H
#define PATH_PLANNING_MESSAGE_PATHPARAM_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <geometry_msgs/Point.h>
#include <geometry_msgs/Point.h>

namespace path_planning
{
template <class ContainerAllocator>
struct PathParam_
{
  typedef PathParam_<ContainerAllocator> Type;

  PathParam_()
    : start()
    , goal()  {
    }
  PathParam_(const ContainerAllocator& _alloc)
    : start(_alloc)
    , goal(_alloc)  {
  (void)_alloc;
    }



   typedef  ::geometry_msgs::Point_<ContainerAllocator>  _start_type;
  _start_type start;

   typedef  ::geometry_msgs::Point_<ContainerAllocator>  _goal_type;
  _goal_type goal;





  typedef boost::shared_ptr< ::path_planning::PathParam_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::path_planning::PathParam_<ContainerAllocator> const> ConstPtr;

}; // struct PathParam_

typedef ::path_planning::PathParam_<std::allocator<void> > PathParam;

typedef boost::shared_ptr< ::path_planning::PathParam > PathParamPtr;
typedef boost::shared_ptr< ::path_planning::PathParam const> PathParamConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::path_planning::PathParam_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::path_planning::PathParam_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace path_planning

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'path_planning': ['/home/cps/catkin_ws_all_0405/src/gml_verify/application/path_planning/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::path_planning::PathParam_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::path_planning::PathParam_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::path_planning::PathParam_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::path_planning::PathParam_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::path_planning::PathParam_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::path_planning::PathParam_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::path_planning::PathParam_<ContainerAllocator> >
{
  static const char* value()
  {
    return "efcee77d261910bec0163bff1fcbe065";
  }

  static const char* value(const ::path_planning::PathParam_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xefcee77d261910beULL;
  static const uint64_t static_value2 = 0xc0163bff1fcbe065ULL;
};

template<class ContainerAllocator>
struct DataType< ::path_planning::PathParam_<ContainerAllocator> >
{
  static const char* value()
  {
    return "path_planning/PathParam";
  }

  static const char* value(const ::path_planning::PathParam_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::path_planning::PathParam_<ContainerAllocator> >
{
  static const char* value()
  {
    return "geometry_msgs/Point start\n\
geometry_msgs/Point goal\n\
================================================================================\n\
MSG: geometry_msgs/Point\n\
# This contains the position of a point in free space\n\
float64 x\n\
float64 y\n\
float64 z\n\
";
  }

  static const char* value(const ::path_planning::PathParam_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::path_planning::PathParam_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.start);
      stream.next(m.goal);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct PathParam_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::path_planning::PathParam_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::path_planning::PathParam_<ContainerAllocator>& v)
  {
    s << indent << "start: ";
    s << std::endl;
    Printer< ::geometry_msgs::Point_<ContainerAllocator> >::stream(s, indent + "  ", v.start);
    s << indent << "goal: ";
    s << std::endl;
    Printer< ::geometry_msgs::Point_<ContainerAllocator> >::stream(s, indent + "  ", v.goal);
  }
};

} // namespace message_operations
} // namespace ros

#endif // PATH_PLANNING_MESSAGE_PATHPARAM_H
