// Generated by gencpp from file event_syn/EventSynergy.msg
// DO NOT EDIT!


#ifndef EVENT_SYN_MESSAGE_EVENTSYNERGY_H
#define EVENT_SYN_MESSAGE_EVENTSYNERGY_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <event_syn/EventBase.h>

namespace event_syn
{
template <class ContainerAllocator>
struct EventSynergy_
{
  typedef EventSynergy_<ContainerAllocator> Type;

  EventSynergy_()
    : base()
    , synergyType()
    , synergyEvent()
    , synergyObject()  {
    }
  EventSynergy_(const ContainerAllocator& _alloc)
    : base(_alloc)
    , synergyType(_alloc)
    , synergyEvent(_alloc)
    , synergyObject(_alloc)  {
  (void)_alloc;
    }



   typedef  ::event_syn::EventBase_<ContainerAllocator>  _base_type;
  _base_type base;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _synergyType_type;
  _synergyType_type synergyType;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _synergyEvent_type;
  _synergyEvent_type synergyEvent;

   typedef std::vector<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > , typename ContainerAllocator::template rebind<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::other >  _synergyObject_type;
  _synergyObject_type synergyObject;





  typedef boost::shared_ptr< ::event_syn::EventSynergy_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::event_syn::EventSynergy_<ContainerAllocator> const> ConstPtr;

}; // struct EventSynergy_

typedef ::event_syn::EventSynergy_<std::allocator<void> > EventSynergy;

typedef boost::shared_ptr< ::event_syn::EventSynergy > EventSynergyPtr;
typedef boost::shared_ptr< ::event_syn::EventSynergy const> EventSynergyConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::event_syn::EventSynergy_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::event_syn::EventSynergy_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace event_syn

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'event_syn': ['/home/cps/catkin_ws_all_0405/src/gml_verify/application/event_syn/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::event_syn::EventSynergy_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::event_syn::EventSynergy_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::event_syn::EventSynergy_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::event_syn::EventSynergy_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::event_syn::EventSynergy_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::event_syn::EventSynergy_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::event_syn::EventSynergy_<ContainerAllocator> >
{
  static const char* value()
  {
    return "8a522657f44ca2b2a7a97cab253c1c6b";
  }

  static const char* value(const ::event_syn::EventSynergy_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x8a522657f44ca2b2ULL;
  static const uint64_t static_value2 = 0xa7a97cab253c1c6bULL;
};

template<class ContainerAllocator>
struct DataType< ::event_syn::EventSynergy_<ContainerAllocator> >
{
  static const char* value()
  {
    return "event_syn/EventSynergy";
  }

  static const char* value(const ::event_syn::EventSynergy_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::event_syn::EventSynergy_<ContainerAllocator> >
{
  static const char* value()
  {
    return "event_syn/EventBase base\n\
string synergyType\n\
string synergyEvent\n\
string[] synergyObject\n\
================================================================================\n\
MSG: event_syn/EventBase\n\
int64 ID\n\
string source\n\
time begintime\n\
time endtime\n\
geometry_msgs/Point startPoint\n\
geometry_msgs/Point endPoint\n\
================================================================================\n\
MSG: geometry_msgs/Point\n\
# This contains the position of a point in free space\n\
float64 x\n\
float64 y\n\
float64 z\n\
";
  }

  static const char* value(const ::event_syn::EventSynergy_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::event_syn::EventSynergy_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.base);
      stream.next(m.synergyType);
      stream.next(m.synergyEvent);
      stream.next(m.synergyObject);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct EventSynergy_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::event_syn::EventSynergy_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::event_syn::EventSynergy_<ContainerAllocator>& v)
  {
    s << indent << "base: ";
    s << std::endl;
    Printer< ::event_syn::EventBase_<ContainerAllocator> >::stream(s, indent + "  ", v.base);
    s << indent << "synergyType: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.synergyType);
    s << indent << "synergyEvent: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.synergyEvent);
    s << indent << "synergyObject[]" << std::endl;
    for (size_t i = 0; i < v.synergyObject.size(); ++i)
    {
      s << indent << "  synergyObject[" << i << "]: ";
      Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.synergyObject[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // EVENT_SYN_MESSAGE_EVENTSYNERGY_H
