# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from event_comm/EventCollaborative.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import event_comm.msg
import genpy
import geometry_msgs.msg
import std_msgs.msg

class EventCollaborative(genpy.Message):
  _md5sum = "d067c2bef3be9d576d17bc244d1ee209"
  _type = "event_comm/EventCollaborative"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """event_comm/EventBase base
string collaborativeType
string collaborativeEvent
string[] collaborativeObject
================================================================================
MSG: event_comm/EventBase
std_msgs/Header header
string eventID
string source
time begintime
time endtime
geometry_msgs/Point startPoint
geometry_msgs/Point endPoint
================================================================================
MSG: std_msgs/Header
# Standard metadata for higher-level stamped data types.
# This is generally used to communicate timestamped data 
# in a particular coordinate frame.
# 
# sequence ID: consecutively increasing ID 
uint32 seq
#Two-integer timestamp that is expressed as:
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')
# time-handling sugar is provided by the client library
time stamp
#Frame this data is associated with
# 0: no frame
# 1: global frame
string frame_id

================================================================================
MSG: geometry_msgs/Point
# This contains the position of a point in free space
float64 x
float64 y
float64 z
"""
  __slots__ = ['base','collaborativeType','collaborativeEvent','collaborativeObject']
  _slot_types = ['event_comm/EventBase','string','string','string[]']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       base,collaborativeType,collaborativeEvent,collaborativeObject

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(EventCollaborative, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.base is None:
        self.base = event_comm.msg.EventBase()
      if self.collaborativeType is None:
        self.collaborativeType = ''
      if self.collaborativeEvent is None:
        self.collaborativeEvent = ''
      if self.collaborativeObject is None:
        self.collaborativeObject = []
    else:
      self.base = event_comm.msg.EventBase()
      self.collaborativeType = ''
      self.collaborativeEvent = ''
      self.collaborativeObject = []

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_3I().pack(_x.base.header.seq, _x.base.header.stamp.secs, _x.base.header.stamp.nsecs))
      _x = self.base.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self.base.eventID
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self.base.source
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_4I6d().pack(_x.base.begintime.secs, _x.base.begintime.nsecs, _x.base.endtime.secs, _x.base.endtime.nsecs, _x.base.startPoint.x, _x.base.startPoint.y, _x.base.startPoint.z, _x.base.endPoint.x, _x.base.endPoint.y, _x.base.endPoint.z))
      _x = self.collaborativeType
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self.collaborativeEvent
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      length = len(self.collaborativeObject)
      buff.write(_struct_I.pack(length))
      for val1 in self.collaborativeObject:
        length = len(val1)
        if python3 or type(val1) == unicode:
          val1 = val1.encode('utf-8')
          length = len(val1)
        buff.write(struct.Struct('<I%ss'%length).pack(length, val1))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.base is None:
        self.base = event_comm.msg.EventBase()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.base.header.seq, _x.base.header.stamp.secs, _x.base.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.base.header.frame_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.base.header.frame_id = str[start:end]
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.base.eventID = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.base.eventID = str[start:end]
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.base.source = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.base.source = str[start:end]
      _x = self
      start = end
      end += 64
      (_x.base.begintime.secs, _x.base.begintime.nsecs, _x.base.endtime.secs, _x.base.endtime.nsecs, _x.base.startPoint.x, _x.base.startPoint.y, _x.base.startPoint.z, _x.base.endPoint.x, _x.base.endPoint.y, _x.base.endPoint.z,) = _get_struct_4I6d().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.collaborativeType = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.collaborativeType = str[start:end]
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.collaborativeEvent = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.collaborativeEvent = str[start:end]
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.collaborativeObject = []
      for i in range(0, length):
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        start = end
        end += length
        if python3:
          val1 = str[start:end].decode('utf-8', 'rosmsg')
        else:
          val1 = str[start:end]
        self.collaborativeObject.append(val1)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_3I().pack(_x.base.header.seq, _x.base.header.stamp.secs, _x.base.header.stamp.nsecs))
      _x = self.base.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self.base.eventID
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self.base.source
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_4I6d().pack(_x.base.begintime.secs, _x.base.begintime.nsecs, _x.base.endtime.secs, _x.base.endtime.nsecs, _x.base.startPoint.x, _x.base.startPoint.y, _x.base.startPoint.z, _x.base.endPoint.x, _x.base.endPoint.y, _x.base.endPoint.z))
      _x = self.collaborativeType
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self.collaborativeEvent
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      length = len(self.collaborativeObject)
      buff.write(_struct_I.pack(length))
      for val1 in self.collaborativeObject:
        length = len(val1)
        if python3 or type(val1) == unicode:
          val1 = val1.encode('utf-8')
          length = len(val1)
        buff.write(struct.Struct('<I%ss'%length).pack(length, val1))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.base is None:
        self.base = event_comm.msg.EventBase()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.base.header.seq, _x.base.header.stamp.secs, _x.base.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.base.header.frame_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.base.header.frame_id = str[start:end]
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.base.eventID = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.base.eventID = str[start:end]
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.base.source = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.base.source = str[start:end]
      _x = self
      start = end
      end += 64
      (_x.base.begintime.secs, _x.base.begintime.nsecs, _x.base.endtime.secs, _x.base.endtime.nsecs, _x.base.startPoint.x, _x.base.startPoint.y, _x.base.startPoint.z, _x.base.endPoint.x, _x.base.endPoint.y, _x.base.endPoint.z,) = _get_struct_4I6d().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.collaborativeType = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.collaborativeType = str[start:end]
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.collaborativeEvent = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.collaborativeEvent = str[start:end]
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.collaborativeObject = []
      for i in range(0, length):
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        start = end
        end += length
        if python3:
          val1 = str[start:end].decode('utf-8', 'rosmsg')
        else:
          val1 = str[start:end]
        self.collaborativeObject.append(val1)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_3I = None
def _get_struct_3I():
    global _struct_3I
    if _struct_3I is None:
        _struct_3I = struct.Struct("<3I")
    return _struct_3I
_struct_4I6d = None
def _get_struct_4I6d():
    global _struct_4I6d
    if _struct_4I6d is None:
        _struct_4I6d = struct.Struct("<4I6d")
    return _struct_4I6d
