# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from event_comm/EventDynamic.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import event_comm.msg
import genpy
import geometry_msgs.msg
import std_msgs.msg

class EventDynamic(genpy.Message):
  _md5sum = "2ccc20968a7c0d24ca90b858f3122b4b"
  _type = "event_comm/EventDynamic"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """event_comm/EventBase base
string dynamicEventName
string dynamicType
string dynamicInfo
================================================================================
MSG: event_comm/EventBase
std_msgs/Header header
string eventID
string source
time begintime
time endtime
geometry_msgs/Point startPoint
geometry_msgs/Point endPoint
================================================================================
MSG: std_msgs/Header
# Standard metadata for higher-level stamped data types.
# This is generally used to communicate timestamped data 
# in a particular coordinate frame.
# 
# sequence ID: consecutively increasing ID 
uint32 seq
#Two-integer timestamp that is expressed as:
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')
# time-handling sugar is provided by the client library
time stamp
#Frame this data is associated with
# 0: no frame
# 1: global frame
string frame_id

================================================================================
MSG: geometry_msgs/Point
# This contains the position of a point in free space
float64 x
float64 y
float64 z
"""
  __slots__ = ['base','dynamicEventName','dynamicType','dynamicInfo']
  _slot_types = ['event_comm/EventBase','string','string','string']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       base,dynamicEventName,dynamicType,dynamicInfo

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(EventDynamic, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.base is None:
        self.base = event_comm.msg.EventBase()
      if self.dynamicEventName is None:
        self.dynamicEventName = ''
      if self.dynamicType is None:
        self.dynamicType = ''
      if self.dynamicInfo is None:
        self.dynamicInfo = ''
    else:
      self.base = event_comm.msg.EventBase()
      self.dynamicEventName = ''
      self.dynamicType = ''
      self.dynamicInfo = ''

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_3I().pack(_x.base.header.seq, _x.base.header.stamp.secs, _x.base.header.stamp.nsecs))
      _x = self.base.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self.base.eventID
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self.base.source
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_4I6d().pack(_x.base.begintime.secs, _x.base.begintime.nsecs, _x.base.endtime.secs, _x.base.endtime.nsecs, _x.base.startPoint.x, _x.base.startPoint.y, _x.base.startPoint.z, _x.base.endPoint.x, _x.base.endPoint.y, _x.base.endPoint.z))
      _x = self.dynamicEventName
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self.dynamicType
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self.dynamicInfo
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.base is None:
        self.base = event_comm.msg.EventBase()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.base.header.seq, _x.base.header.stamp.secs, _x.base.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.base.header.frame_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.base.header.frame_id = str[start:end]
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.base.eventID = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.base.eventID = str[start:end]
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.base.source = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.base.source = str[start:end]
      _x = self
      start = end
      end += 64
      (_x.base.begintime.secs, _x.base.begintime.nsecs, _x.base.endtime.secs, _x.base.endtime.nsecs, _x.base.startPoint.x, _x.base.startPoint.y, _x.base.startPoint.z, _x.base.endPoint.x, _x.base.endPoint.y, _x.base.endPoint.z,) = _get_struct_4I6d().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.dynamicEventName = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.dynamicEventName = str[start:end]
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.dynamicType = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.dynamicType = str[start:end]
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.dynamicInfo = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.dynamicInfo = str[start:end]
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_3I().pack(_x.base.header.seq, _x.base.header.stamp.secs, _x.base.header.stamp.nsecs))
      _x = self.base.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self.base.eventID
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self.base.source
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_4I6d().pack(_x.base.begintime.secs, _x.base.begintime.nsecs, _x.base.endtime.secs, _x.base.endtime.nsecs, _x.base.startPoint.x, _x.base.startPoint.y, _x.base.startPoint.z, _x.base.endPoint.x, _x.base.endPoint.y, _x.base.endPoint.z))
      _x = self.dynamicEventName
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self.dynamicType
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self.dynamicInfo
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.base is None:
        self.base = event_comm.msg.EventBase()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.base.header.seq, _x.base.header.stamp.secs, _x.base.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.base.header.frame_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.base.header.frame_id = str[start:end]
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.base.eventID = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.base.eventID = str[start:end]
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.base.source = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.base.source = str[start:end]
      _x = self
      start = end
      end += 64
      (_x.base.begintime.secs, _x.base.begintime.nsecs, _x.base.endtime.secs, _x.base.endtime.nsecs, _x.base.startPoint.x, _x.base.startPoint.y, _x.base.startPoint.z, _x.base.endPoint.x, _x.base.endPoint.y, _x.base.endPoint.z,) = _get_struct_4I6d().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.dynamicEventName = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.dynamicEventName = str[start:end]
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.dynamicType = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.dynamicType = str[start:end]
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.dynamicInfo = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.dynamicInfo = str[start:end]
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_3I = None
def _get_struct_3I():
    global _struct_3I
    if _struct_3I is None:
        _struct_3I = struct.Struct("<3I")
    return _struct_3I
_struct_4I6d = None
def _get_struct_4I6d():
    global _struct_4I6d
    if _struct_4I6d is None:
        _struct_4I6d = struct.Struct("<4I6d")
    return _struct_4I6d
