// Generated by gencpp from file event_comm/UAVState.msg
// DO NOT EDIT!


#ifndef EVENT_COMM_MESSAGE_UAVSTATE_H
#define EVENT_COMM_MESSAGE_UAVSTATE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <geometry_msgs/Point.h>

namespace event_comm
{
template <class ContainerAllocator>
struct UAVState_
{
  typedef UAVState_<ContainerAllocator> Type;

  UAVState_()
    : UAVnum(0)
    , Point()  {
    }
  UAVState_(const ContainerAllocator& _alloc)
    : UAVnum(0)
    , Point(_alloc)  {
  (void)_alloc;
    }



   typedef uint64_t _UAVnum_type;
  _UAVnum_type UAVnum;

   typedef  ::geometry_msgs::Point_<ContainerAllocator>  _Point_type;
  _Point_type Point;





  typedef boost::shared_ptr< ::event_comm::UAVState_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::event_comm::UAVState_<ContainerAllocator> const> ConstPtr;

}; // struct UAVState_

typedef ::event_comm::UAVState_<std::allocator<void> > UAVState;

typedef boost::shared_ptr< ::event_comm::UAVState > UAVStatePtr;
typedef boost::shared_ptr< ::event_comm::UAVState const> UAVStateConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::event_comm::UAVState_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::event_comm::UAVState_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace event_comm

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'event_comm': ['/home/cps/catkin_ws_all_0405/src/gml_verify/micro_embedded_collaborative_engine/event_comm/msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::event_comm::UAVState_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::event_comm::UAVState_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::event_comm::UAVState_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::event_comm::UAVState_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::event_comm::UAVState_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::event_comm::UAVState_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::event_comm::UAVState_<ContainerAllocator> >
{
  static const char* value()
  {
    return "82010c98432e82a612d456b09f37f399";
  }

  static const char* value(const ::event_comm::UAVState_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x82010c98432e82a6ULL;
  static const uint64_t static_value2 = 0x12d456b09f37f399ULL;
};

template<class ContainerAllocator>
struct DataType< ::event_comm::UAVState_<ContainerAllocator> >
{
  static const char* value()
  {
    return "event_comm/UAVState";
  }

  static const char* value(const ::event_comm::UAVState_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::event_comm::UAVState_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint64 UAVnum\n\
geometry_msgs/Point Point\n\
================================================================================\n\
MSG: geometry_msgs/Point\n\
# This contains the position of a point in free space\n\
float64 x\n\
float64 y\n\
float64 z\n\
";
  }

  static const char* value(const ::event_comm::UAVState_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::event_comm::UAVState_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.UAVnum);
      stream.next(m.Point);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct UAVState_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::event_comm::UAVState_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::event_comm::UAVState_<ContainerAllocator>& v)
  {
    s << indent << "UAVnum: ";
    Printer<uint64_t>::stream(s, indent + "  ", v.UAVnum);
    s << indent << "Point: ";
    s << std::endl;
    Printer< ::geometry_msgs::Point_<ContainerAllocator> >::stream(s, indent + "  ", v.Point);
  }
};

} // namespace message_operations
} // namespace ros

#endif // EVENT_COMM_MESSAGE_UAVSTATE_H
