# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from vsform_test/Goal.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import geometry_msgs.msg

class Goal(genpy.Message):
  _md5sum = "b0c8263c41fcbdd38a6148d2ecdf8e38"
  _type = "vsform_test/Goal"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """geometry_msgs/Point32 frame_pos # frame position
geometry_msgs/Point32 frame_vel # frame velocity
float32 path_width # path width
================================================================================
MSG: geometry_msgs/Point32
# This contains the position of a point in free space(with 32 bits of precision).
# It is recommeded to use Point wherever possible instead of Point32.  
# 
# This recommendation is to promote interoperability.  
#
# This message is designed to take up less space when sending
# lots of points at once, as in the case of a PointCloud.  

float32 x
float32 y
float32 z"""
  __slots__ = ['frame_pos','frame_vel','path_width']
  _slot_types = ['geometry_msgs/Point32','geometry_msgs/Point32','float32']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       frame_pos,frame_vel,path_width

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(Goal, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.frame_pos is None:
        self.frame_pos = geometry_msgs.msg.Point32()
      if self.frame_vel is None:
        self.frame_vel = geometry_msgs.msg.Point32()
      if self.path_width is None:
        self.path_width = 0.
    else:
      self.frame_pos = geometry_msgs.msg.Point32()
      self.frame_vel = geometry_msgs.msg.Point32()
      self.path_width = 0.

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_7f().pack(_x.frame_pos.x, _x.frame_pos.y, _x.frame_pos.z, _x.frame_vel.x, _x.frame_vel.y, _x.frame_vel.z, _x.path_width))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.frame_pos is None:
        self.frame_pos = geometry_msgs.msg.Point32()
      if self.frame_vel is None:
        self.frame_vel = geometry_msgs.msg.Point32()
      end = 0
      _x = self
      start = end
      end += 28
      (_x.frame_pos.x, _x.frame_pos.y, _x.frame_pos.z, _x.frame_vel.x, _x.frame_vel.y, _x.frame_vel.z, _x.path_width,) = _get_struct_7f().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_7f().pack(_x.frame_pos.x, _x.frame_pos.y, _x.frame_pos.z, _x.frame_vel.x, _x.frame_vel.y, _x.frame_vel.z, _x.path_width))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.frame_pos is None:
        self.frame_pos = geometry_msgs.msg.Point32()
      if self.frame_vel is None:
        self.frame_vel = geometry_msgs.msg.Point32()
      end = 0
      _x = self
      start = end
      end += 28
      (_x.frame_pos.x, _x.frame_pos.y, _x.frame_pos.z, _x.frame_vel.x, _x.frame_vel.y, _x.frame_vel.z, _x.path_width,) = _get_struct_7f().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_7f = None
def _get_struct_7f():
    global _struct_7f
    if _struct_7f is None:
        _struct_7f = struct.Struct("<7f")
    return _struct_7f
