# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from sml_dyn/Event.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import genpy
import geometry_msgs.msg

class Event(genpy.Message):
  _md5sum = "22829605e857c5733b3d0b8eab5f82ce"
  _type = "sml_dyn/Event"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """uint64 id                  # 事件的标识
string name                # 事件的名字
uint8 prior                # 事件的优先级 默认为0 越大越优先
time time                  # 事件的时间
geometry_msgs/Point pos    # 事件的位置
geometry_msgs/Point data   # 事件传输的数据
================================================================================
MSG: geometry_msgs/Point
# This contains the position of a point in free space
float64 x
float64 y
float64 z
"""
  __slots__ = ['id','name','prior','time','pos','data']
  _slot_types = ['uint64','string','uint8','time','geometry_msgs/Point','geometry_msgs/Point']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       id,name,prior,time,pos,data

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(Event, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.id is None:
        self.id = 0
      if self.name is None:
        self.name = ''
      if self.prior is None:
        self.prior = 0
      if self.time is None:
        self.time = genpy.Time()
      if self.pos is None:
        self.pos = geometry_msgs.msg.Point()
      if self.data is None:
        self.data = geometry_msgs.msg.Point()
    else:
      self.id = 0
      self.name = ''
      self.prior = 0
      self.time = genpy.Time()
      self.pos = geometry_msgs.msg.Point()
      self.data = geometry_msgs.msg.Point()

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self.id
      buff.write(_get_struct_Q().pack(_x))
      _x = self.name
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_B2I6d().pack(_x.prior, _x.time.secs, _x.time.nsecs, _x.pos.x, _x.pos.y, _x.pos.z, _x.data.x, _x.data.y, _x.data.z))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.time is None:
        self.time = genpy.Time()
      if self.pos is None:
        self.pos = geometry_msgs.msg.Point()
      if self.data is None:
        self.data = geometry_msgs.msg.Point()
      end = 0
      start = end
      end += 8
      (self.id,) = _get_struct_Q().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.name = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.name = str[start:end]
      _x = self
      start = end
      end += 57
      (_x.prior, _x.time.secs, _x.time.nsecs, _x.pos.x, _x.pos.y, _x.pos.z, _x.data.x, _x.data.y, _x.data.z,) = _get_struct_B2I6d().unpack(str[start:end])
      self.time.canon()
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self.id
      buff.write(_get_struct_Q().pack(_x))
      _x = self.name
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_B2I6d().pack(_x.prior, _x.time.secs, _x.time.nsecs, _x.pos.x, _x.pos.y, _x.pos.z, _x.data.x, _x.data.y, _x.data.z))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.time is None:
        self.time = genpy.Time()
      if self.pos is None:
        self.pos = geometry_msgs.msg.Point()
      if self.data is None:
        self.data = geometry_msgs.msg.Point()
      end = 0
      start = end
      end += 8
      (self.id,) = _get_struct_Q().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.name = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.name = str[start:end]
      _x = self
      start = end
      end += 57
      (_x.prior, _x.time.secs, _x.time.nsecs, _x.pos.x, _x.pos.y, _x.pos.z, _x.data.x, _x.data.y, _x.data.z,) = _get_struct_B2I6d().unpack(str[start:end])
      self.time.canon()
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_B2I6d = None
def _get_struct_B2I6d():
    global _struct_B2I6d
    if _struct_B2I6d is None:
        _struct_B2I6d = struct.Struct("<B2I6d")
    return _struct_B2I6d
_struct_Q = None
def _get_struct_Q():
    global _struct_Q
    if _struct_Q is None:
        _struct_Q = struct.Struct("<Q")
    return _struct_Q
